spring:
  application:
    name: FbLoginAuth

security:
  oauth2:
    client:
      clientId: 126200146115791
      clientSecret: 9c1717bf3f919765895d36ecfd52fe88
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me